Auth
wintradequiz/WinTrade-Quiz pull request #4
Opened 2021-04-22 15:42 UTC by lsmn9

Сам фрагмент и небольшие дополнения в зависимостях

2021-04-22 17:14 UTC, agafonovilya requested changes

2021-04-22 17:14 UTC, agafonovilya commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +        googleSignInClient = GoogleSignIn.getClient(App.instance, gso)
Может в отдельный метод вынести все,что связано с получением клиента?

2021-04-22 17:14 UTC, agafonovilya commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +            disableSign();
Метод disableSign логично запихнуть в метод updateUI, т.к. название метода updateUI как раз говорит о том, что в нем должен обновится UI

2021-04-22 17:14 UTC, agafonovilya commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +    private fun initViews(){
А зачем инициализировать кнопки? Мы же на котлине. Можем использовать Kotlin Android Extensions

2021-04-22 17:14 UTC, agafonovilya commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +    private fun enableSign() {
Предлагаю переименовать в enableSignButton

2021-04-22 17:14 UTC, agafonovilya commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +    private fun disableSign() {
Предлагаю переименовать в disableSignButton

2021-04-23 16:26 UTC, wintradequiz commented on app/src/main/java/ru/wintrade/wintradequiz/MainActivity.kt
> +            .commit()
Можно, но смысла в нашем случае здесь нет - навигация сама управляет фрагментами. Потом отрефакторим.

2021-04-23 16:28 UTC, wintradequiz commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +        googleSignInClient = GoogleSignIn.getClient(App.instance, gso)
private lateinit var googleSignInClient: GoogleSignInClient
    private lateinit var buttonSignIn: SignInButton
    private lateinit var buttonSingOut: MaterialButton

Тут биндинг не помешает.

2021-04-23 16:29 UTC, wintradequiz commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +    private fun initViews(){
Экстеншены задепрекэйтили. Биндинг рулит ))

2021-04-23 16:29 UTC, wintradequiz approved these changes

2021-04-23 16:31 UTC, wintradequiz commented on app/src/main/java/ru/wintrade/wintradequiz/auth/AuthFragment.kt
> +        googleSignInClient = GoogleSignIn.getClient(App.instance, gso)
Чтобы Сергею с биндингом не разбираться, я сделаю - он посмотрит и будет так же делать.

2021-04-25 16:07 UTC, merged